development: &default
  api_v1_root: <%= "#{ENV['GRAVITY_API_ROOT'] || 'https://stagingapi.artsy.net'}/api/v1" %>
  xapp_token:  <%= ENV['GRAVITY_JWT'] || 'https://media.giphy.com/media/yow6i0Zmp7G24/giphy.gif' %>
  artwork_cache_in_seconds: <%= (ENV['ARTWORK_CACHE_IN_SECONDS'] || '600').to_i %>
  partner_cache_in_seconds: <%= (ENV['PARTNER_CACHE_IN_SECONDS'] || '600').to_i %>
test:
  <<: *default
  api_v1_root: 'http://exchange-test-gravity.biz'
production:
  <<: *default